---
- name: Cleanup customer resources and notify
  hosts: localhost
  gather_facts: false
  vars:
    smtp_server: smtp.infosys.com
    customer_email: "customer@example.com"
    change_ticket_number: "CHG123456"
    compartment_name: "MyTestCompartment"
    customer_name: "Customer Team"
    email_template: "email.j2"

  tasks:
    - name: Run the Python resource cleanup script
      command: >
        python3 py-scripts/list_resources.py
        --compartment-id {{ compartment_id }}
        --region {{ region }}
        --delete
      register: resource_output

    - name: Debug resource output (optional)
      debug:
        var: resource_output.stdout_lines

    - name: Set empty deleted_resources_list
      set_fact:
        deleted_resources_list: []

    - name: Extract deleted resources from Python output
      set_fact:
        deleted_resources_list: "{{ deleted_resources_list + [ resource_type ~ ': ' ~ resource_name ] }}"
      loop: "{{ resource_output.stdout_lines }}"
      when: item is search('\\[DELETE\\] ')
      vars:
        resource_type: "{{ item.split()[1] }}"
        resource_name: "{{ item.split('->')[1].split('(')[0] | trim }}"

    - name: Send email notification if resources were deleted
      community.general.mail:
        host: "{{ smtp_server }}"
        port: 25
        subject: "OCI Resources Deleted for {{ compartment_name }} ({{ change_ticket_number }})"
        from: "cloud@infosys.com"
        to:
          - "{{ customer_email }}"
        cc:
          - "cloud@infosys.com"
        body: "{{ lookup('template', email_template) }}"
        subtype: html
        charset: utf8
      when: deleted_resources_list | length > 0
